name: Update Profile

on:
  schedule:
    - cron: '0 0 * * 0'  # Ejecutar cada domingo a medianoche
  workflow_dispatch:  # Permitir ejecuci칩n manual

jobs:
  update-profile:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Update README
      run: |
        echo "Perfil actualizado autom치ticamente el $(date)" >> README.md
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "游댃 Actualizaci칩n autom치tica del perfil" || exit 0
        git push 